### ISSUE TITLE
Issue after latest HA update 2024.1

### ISSUE THREAD

**Issue by xHuubx** [danieldotnl/ha-multiscrape#311]
After installing the latest update I get following error:

_Setup failed for custom integration 'multiscrape': Requirements for multiscrape not found: ['lxml==4.9.1']._

Does anyone has a clue how to fix this?

**Comment by 1nv4lidus3r** [comment]
+1,
I get the same.

**Comment by xHuubx** [comment]
The latest update solved the issue!

**Comment by tOOmki** [comment]
I still have problem.

I try branch homeassistant-2024.x but no success. 

Version core-2024.1.6
Home Assistant OS

Logger: homeassistant.util.package
Source: util/package.py:102
First occurred: 21:01:58 (3 occurrences)
Last logged: 21:02:11

Unable to install package lxml==4.9.1: ERROR: Cannot install lxml==4.9.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
